blacklistedOres = []
spawnWithGuideBook = false
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableAe2Integration = true
generateOres = true
