blacklistedOres = []
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableAe2Integration = true
generateOres = true
