
[renderers]

	[renderers.inventory_renderer]
		#Screen side to render status effects on.
		#Allowed Values: LEFT, RIGHT
		screen_side = "LEFT"
		#Maximum amount of status effects rendered in a single column.
		#Range: 1 ~ 255
		max_rows = 255
		#Show a tooltip when hovering over an effect widget.
		hovering_tooltip = true
		#Minimum screen border distance for effect widgets.
		#Range: > 0
		screen_border_distance = 3
		#Alpha value for effect widgets.
		#Range: 0.0 ~ 1.0
		widget_alpha = 1.0
		#Allow effect renderer to fall back to a more compact version (when available) if not enough screen space exists. Otherwise effect widgets might run off-screen.
		allow_fallback = true
		#Exclude certain menus from showing active status effects. Useful when effect icons overlap with other screen elements.
		menu_blacklist = ["curios:curios_container"]
		#Effect renderer to be used.
		#This setting might not be respected when not enough screen space is available. To force this setting disable "allow_fallback".
		#Allowed Values: NONE, COMPACT, VANILLA
		renderer_type = "COMPACT"
		#Maximum amount of status effects rendered in a single row.
		#Range: 1 ~ 255
		max_columns = 5
		#Show remaining status effect duration on tooltip.
		tooltip_duration = true
		#What to do when there are more effects to display than there is room on-screen.
		#Allowed Values: CONDENSE, SKIP
		overflow_mode = "CONDENSE"
		#Respect vanilla's "hideParticles" flag which prevents a status effect from showing when set via commands.
		respect_hide_particles = false
		#Render active status effects in every menu screen, not just in the player inventory.
		effects_everywhere = true
		#Space between individual effect widgets on y-axis.
		#Range: > 0
		widget_space_y = 1
		#Space between individual effect widgets on x-axis.
		#Range: > 0
		widget_space_x = 1

	[renderers.hud_renderer]
		#Maximum amount of status effects rendered in a single row.
		#Range: 1 ~ 255
		max_columns = 5
		#Screen side to render status effects on.
		#Allowed Values: LEFT, RIGHT
		screen_side = "RIGHT"
		#Maximum amount of status effects rendered in a single column.
		#Range: 1 ~ 255
		max_rows = 255
		#What to do when there are more effects to display than there is room on-screen.
		#Allowed Values: CONDENSE, SKIP
		overflow_mode = "CONDENSE"
		#Respect vanilla's "hideParticles" flag which prevents a status effect from showing when set via commands.
		respect_hide_particles = true
		#Alpha value for effect widgets.
		#Range: 0.0 ~ 1.0
		widget_alpha = 0.85
		#Allow effect renderer to fall back to a more compact version (when available) if not enough screen space exists. Otherwise effect widgets might run off-screen.
		allow_fallback = false
		#Offset on x-axis.
		#Range: > 0
		offset_x = 3
		#Offset on y-axis.
		#Range: > 0
		offset_y = 3
		#Space between individual effect widgets on y-axis.
		#Range: > 0
		widget_space_y = 1
		#Space between individual effect widgets on x-axis.
		#Range: > 0
		widget_space_x = 1
		#Effect renderer to be used.
		#This setting might not be respected when not enough screen space is available. To force this setting disable "allow_fallback".
		#Allowed Values: NONE, COMPACT, VANILLA
		renderer_type = "COMPACT"

[widgets]

	[widgets.compact_widget]
		#Should ambient effect widgets have a cyan colored border.
		ambient_border = true
		#Display string to be used for an effect duration that is too long to show.
		#Allowed Values: VANILLA, INFINITY, NONE
		long_duration_string = "INFINITY"
		#Should the effect icon start to blink when the effect is running out.
		blinking_alpha = true
		#Draw harmful effects on a separate line from beneficial ones. This is turned on in vanilla.
		separate_effects = false
		#Show duration for ambient effects.
		ambient_duration = false
		#Top corner to draw effect amplifier in, or none.
		#Allowed Values: NONE, TOP_LEFT, TOP_RIGHT
		effect_amplifier = "TOP_RIGHT"
		#Effect amplifier color. Setting this to "EFFECT" will use potion color.
		#Allowed Values: EFFECT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		amplifier_color = "WHITE"
		#Effect duration color. Setting this to "EFFECT" will use potion color.
		#Allowed Values: EFFECT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		duration_color = "GRAY"

	[widgets.vanilla_widget]
		#Should ambient effect widgets have a cyan colored border.
		ambient_border = true
		#Display string to be used for an effect duration that is too long to show.
		#Allowed Values: VANILLA, INFINITY, NONE
		long_duration_string = "VANILLA"
		#Should the effect icon start to blink when the effect is running out.
		blinking_alpha = true
		#Effect name color. Setting this to "EFFECT" will use potion color.
		#Allowed Values: EFFECT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		name_color = "WHITE"
		#Show duration for ambient effects.
		ambient_duration = true
		#Effect duration color. Setting this to "EFFECT" will use potion color.
		#Allowed Values: EFFECT, BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
		duration_color = "GRAY"

