name = "Adorn"
filename = "Adorn-3.2.0+1.18.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3609/858/Adorn-3.2.0+1.18.1-fabric.jar"
hash-format = "murmur2"
hash = "3786263245"

[update]
[update.curseforge]
file-id = 3609858
project-id = 320215
