name = "AdventureZ"
filename = "adventurez-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/98/adventurez-1.3.0.jar"
hash-format = "murmur2"
hash = "2064757285"

[update]
[update.curseforge]
file-id = 3482098
project-id = 390991
