name = "Alloy Forgery"
filename = "wraith-alloy-forgery-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3505/805/wraith-alloy-forgery-2.0.5.jar"
hash-format = "murmur2"
hash = "2681571916"

[update]
[update.curseforge]
file-id = 3505805
project-id = 438718
