name = "Auth Me"
filename = "authme-mc1.18.1-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/439/authme-mc1.18.1-2.2.0.jar"
hash-format = "murmur2"
hash = "2503715725"

[update]
[update.curseforge]
file-id = 3569439
project-id = 356643
