name = "Axes Are Weapons (Fabric/Forge)"
filename = "AxesAreWeapons-1.3-1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3384/705/AxesAreWeapons-1.3-1.17.jar"
hash-format = "murmur2"
hash = "777362754"

[update]
[update.curseforge]
file-id = 3384705
project-id = 456457
release-channel = "beta"
