name = "Bosses of Mass Destruction"
filename = "BOMD-1.3.1-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3477/697/BOMD-1.3.1-1.17.1.jar"
hash-format = "murmur2"
hash = "205208080"

[update]
[update.curseforge]
file-id = 3477697
project-id = 438365
release-channel = "beta"
