name = "Bosses of Mass Destruction"
filename = "BOMD-1.3.2-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3491/486/BOMD-1.3.2-1.17.1.jar"
hash-format = "murmur2"
hash = "2084239103"

[update]
[update.curseforge]
file-id = 3491486
project-id = 438365
