name = "Bosses of Mass Destruction"
filename = "BOMD-1.3.4-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/287/BOMD-1.3.4-1.18.jar"
hash-format = "murmur2"
hash = "2259564240"

[update]
[update.curseforge]
file-id = 3631287
project-id = 438365
