name = "Collective (Fabric)"
filename = "collective-fabric-1.17.x-1.44.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3490/828/collective-fabric-1.17.x-1.44.jar"
hash-format = "murmur2"
hash = "3463611559"

[update]
[update.curseforge]
file-id = 3490828
project-id = 526606
