name = "Collective (Fabric)"
filename = "collective-fabric-1.18.x-3.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3568/581/collective-fabric-1.18.x-3.14.jar"
hash-format = "murmur2"
hash = "740591963"

[update]
[update.curseforge]
file-id = 3568581
project-id = 526606
