name = "Collective (Fabric)"
filename = "collective-fabric-1.18.x-4.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3654/799/collective-fabric-1.18.x-4.9.jar"
hash-format = "murmur2"
hash = "881285286"

[update]
[update.curseforge]
file-id = 3654799
project-id = 526606
