name = "Companion ğŸ• (Fabric)"
filename = "Companion-1.18.1-fabric-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/584/Companion-1.18.1-fabric-1.2.1.jar"
hash-format = "murmur2"
hash = "3979885406"

[update]
[update.curseforge]
file-id = 3652584
project-id = 560280
