name = "Continuity"
filename = "continuity-1.1.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3655/794/continuity-1.1.0+1.18.jar"
hash-format = "murmur2"
hash = "904462195"

[update]
[update.curseforge]
file-id = 3655794
project-id = 531351
