name = "CraftPresence"
filename = "CraftPresence-Fabric-1.17.1-Release-1.8.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3475/682/CraftPresence-Fabric-1.17.1-Release-1.8.8.jar"
hash-format = "murmur2"
hash = "3688934347"

[update]
[update.curseforge]
file-id = 3475682
project-id = 297038
release-channel = "beta"
