name = "Eldritch Mobs"
filename = "eldritch-mobs-1.10.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/75/eldritch-mobs-1.10.2.jar"
hash-format = "murmur2"
hash = "3260137899"

[update]
[update.curseforge]
file-id = 3580075
project-id = 392015
