name = "Fast Furnace for Fabric"
filename = "fastfurnace-1.17-3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/874/fastfurnace-1.17-3.0.jar"
hash-format = "murmur2"
hash = "3000917254"

[update]
[update.curseforge]
file-id = 3348874
project-id = 364540
