name = "FerriteCore (Fabric)"
filename = "ferritecore-4.1.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/642/ferritecore-4.1.2-fabric.jar"
hash-format = "murmur2"
hash = "2212012912"

[update]
[update.curseforge]
file-id = 3652642
project-id = 459857
