name = "Krypton"
filename = "krypton-0.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3378/767/krypton-0.1.4.jar"
hash-format = "murmur2"
hash = "362803332"

[update]
[update.curseforge]
file-id = 3378767
project-id = 428912
