name = "Magic Fungi"
filename = "magicfungi-0.6.3-BETA+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/403/magicfungi-0.6.3-BETA+1.18.jar"
hash-format = "murmur2"
hash = "167674451"

[update]
[update.curseforge]
file-id = 3613403
project-id = 506412
