name = "MaLiLib"
filename = "malilib-fabric-1.17.1-0.10.0-dev.26.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3498/871/malilib-fabric-1.17.1-0.10.0-dev.26.jar"
hash-format = "murmur2"
hash = "326898747"

[update]
[update.curseforge]
file-id = 3498871
project-id = 303119
