name = "MC Dungeons Armors"
filename = "mcda-1.7.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3498/75/mcda-1.7.15.jar"
hash-format = "murmur2"
hash = "1958404657"

[update]
[update.curseforge]
file-id = 3498075
project-id = 426206
