name = "MC Dungeons Armors"
filename = "mcda-1.7.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/448/mcda-1.7.12.jar"
hash-format = "murmur2"
hash = "2744654865"

[update]
[update.curseforge]
file-id = 3482448
project-id = 426206
release-channel = "beta"
