name = "MC Dungeons Artifacts"
filename = "mcdar-1.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3494/181/mcdar-1.4.2.jar"
hash-format = "murmur2"
hash = "2305642566"

[update]
[update.curseforge]
file-id = 3494181
project-id = 476788
