name = "MC Dungeons Armors"
filename = "mcda-1.7.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3487/159/mcda-1.7.13.jar"
hash-format = "murmur2"
hash = "3552476950"

[update]
[update.curseforge]
file-id = 3487159
project-id = 426206
