name = "More Villages Mod"
filename = "morevillagesmod-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3468/819/morevillagesmod-1.0.0.jar"
hash-format = "murmur2"
hash = "3883982678"

[update]
[update.curseforge]
file-id = 3468819
project-id = 523090
