name = "Motschen's Puddles"
filename = "puddles-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3306/770/puddles-1.1.0.jar"
hash-format = "murmur2"
hash = "1321417908"

[update]
[update.curseforge]
file-id = 3306770
project-id = 463169
