name = "Mouse Tweaks"
filename = "MouseTweaks-fabric-mc1.18-2.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3601/896/MouseTweaks-fabric-mc1.18-2.22.jar"
hash-format = "murmur2"
hash = "1440569453"

[update]
[update.curseforge]
file-id = 3601896
project-id = 60089
