name = "Mythic Mounts"
filename = "mythic-mounts-1.18-4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3570/219/mythic-mounts-1.18-4.0.jar"
hash-format = "murmur2"
hash = "326806096"

[update]
[update.curseforge]
file-id = 3570219
project-id = 517650
