name = "NinjaPhenix's Container Library"
filename = "ninjaphenix-container-library-1.2.10+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3591/317/ninjaphenix-container-library-1.2.10+1.18.jar"
hash-format = "murmur2"
hash = "2014269087"

[update]
[update.curseforge]
file-id = 3591317
project-id = 530668
