name = "Origins (Fabric)"
filename = "Origins-1.18-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3561/745/Origins-1.18-1.3.1.jar"
hash-format = "murmur2"
hash = "867060022"

[update]
[update.curseforge]
file-id = 3561745
project-id = 391943
