name = "Patchouli (Fabric)"
filename = "Patchouli-1.18.1-65-FABRIC.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/726/Patchouli-1.18.1-65-FABRIC.jar"
hash-format = "murmur2"
hash = "4109706807"

[update]
[update.curseforge]
file-id = 3630726
project-id = 393236
