name = "Pehkui"
filename = "Pehkui-3.1.0+1.14.4-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3577/68/Pehkui-3.1.0+1.14.4-1.18.1.jar"
hash-format = "murmur2"
hash = "3400382429"

[update]
[update.curseforge]
file-id = 3577068
project-id = 319596
