name = "Pehkui"
filename = "Pehkui-2.5.3+1.14.4-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3501/603/Pehkui-2.5.3+1.14.4-1.18.jar"
hash-format = "murmur2"
hash = "2800763895"

[update]
[update.curseforge]
file-id = 3501603
project-id = 319596
