name = "Pling"
filename = "pling-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/632/pling-1.5.0.jar"
hash-format = "murmur2"
hash = "1371210914"

[update]
[update.curseforge]
file-id = 3550632
project-id = 365521
