name = "Rat's Mischief ğŸ€"
filename = "ratsmischief-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3579/221/ratsmischief-1.3.4.jar"
hash-format = "murmur2"
hash = "3672806131"

[update]
[update.curseforge]
file-id = 3579221
project-id = 431787
