name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures_fabric-2.4.2+1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3497/669/repurposed_structures_fabric-2.4.2+1.17.1.jar"
hash-format = "murmur2"
hash = "1235875972"

[update]
[update.curseforge]
file-id = 3497669
project-id = 391366
