name = "Skin Layers 3D (Fabric/Forge)"
filename = "3dSkinLayers-Fabric-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/751/3dSkinLayers-Fabric-1.3.1.jar"
hash-format = "murmur2"
hash = "956859911"

[update]
[update.curseforge]
file-id = 3541751
project-id = 521480
