name = "Sound Physics Remastered"
filename = "soundphysics-fabric-1.18.1-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/527/soundphysics-fabric-1.18.1-1.0.4.jar"
hash-format = "murmur2"
hash = "2037384813"

[update]
[update.curseforge]
file-id = 3599527
project-id = 535489
