name = "WorldEdit"
filename = "worldedit-mod-7.2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3433/990/worldedit-mod-7.2.6.jar"
hash-format = "murmur2"
hash = "3350066961"

[update]
[update.curseforge]
file-id = 3433990
project-id = 225608
